### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by marek130**
Update version.rb and CHANGELOG.md

### CODE REVIEW

**Comment by marek130** [comment]
@zilchms can we release a new version? many thanks!

**Comment by zilchms** [comment]
Sure thing :)
Do you see any reason to make this release a major release? As far as i can tell, there have only been non-breaking enhancements and therefore the new version should be 0.10.0, right?

**Comment by marek130** [comment]
@zilchms great question :) Even it is a small update, from my point of view, moving from Hiera v3 to v5 is significat change in terms of backward-incompatible.

If you were able to use the hiera check in 0.9.0 version it will not be possible with this update. There is totally diferent structure of hiera.yaml.

For example, every path in hierarchy is value of the key ‘path’ or ‘paths’.

**Comment by zilchms** [comment]
can you recreate the changelog again? i changed the label of the PR to correctly reflect the changes made

**Comment by zilchms** [comment]
sorry to ask again, can you regenerate it a second time? still getting used to doing releases properly...

**Comment by marek130** [comment]
> sorry to ask again, can you regenerate it a second time? still getting used to doing releases properly...

There is no big difference after I regenerated again.. Only this:

```
-## [1.0.0](https://github.com/voxpupuli/puppet-ghostbuster/tree/1.0.0) (2023-11-10)
+## [1.0.0](https://github.com/voxpupuli/puppet-ghostbuster/tree/1.0.0) (2023-11-11)
```

**Comment by zilchms** [comment]
yea, error on my part. no second regenerate needed. sorry about that

**Review by zilchms — APPROVED** [review]

**Comment by zilchms** [comment]
will take a bit until the gem is available, need to get someone with higher permissions to trigger a full gem release :)

**Comment by marek130** [comment]
Many thanks anyway!

**Comment by zilchms** [comment]
For reference: a official release of the ruby gem is blocked by #66 which was only partly completed.

**Comment by zilchms** [comment]
last update on this: release is now out as migration is fully completed

**Pull request merged**
