### PR TITLE
add preconnect option. fix #4

### LINKED ISSUE #4: Add preconnect parameter
So that we can open an ssh tunnel to the host that hosts the puppetdb

### PR DESCRIPTION
**Pull request by saimonn**
Enjoy with 'ssh -Nf -Ldbport:localhost:dbport user@puppetdbhost'

### CODE REVIEW

**Comment by saimonn** [comment]
@mcanevet  here you are.

**Comment by mcanevet** [comment]
@saimonn it work fine when using it with command line arguments, but I can't figure out how to make it work in `.puppet-ghostbuster.rb`. I tried with:

```
-pssh\ -f\ -L8083:localhost:8080\ root@puppetdb.tld\ sleep\ 30
-p'ssh -f -L8083:localhost:8080 root@puppetdb.tld sleep 30'
```

**Comment by saimonn** [comment]
I tried with:

```
$ cat .puppet-ghostbuster.rc 
-ldebug
-shttp://localhost:8083
-p'ssh -Nf -L8083:localhost:8080 user@puppet.db.host'
```

log-level debug and server options are working as expected.

But optparser.rb seems to handle weirdly options loaded from file when they contain space. This need more investigation.

**Comment by mattbostock** [comment]
Would it perhaps be simpler to create an SSH tunnel separate to puppet-ghostbuster?

**Comment by saimonn** [comment]
@mattbostock Yes, it would be much simpler, but then it could not be automatically launched by a third party scripts

**Comment by mcanevet** [comment]
@saimonn I close this as we are using puppet-lint plugins now

**Pull request closed without merging**
